export { default as Table} from './Table'
export { default as TableHead} from './TableHead'
export { default as TableBody} from './TableBody'
export { default as Tr} from './Tr'
export { default as Th} from './Th'
export { default as Td} from './Td'